[package]
name = "rust-dbus-bluez"
version = "0.1.0"
authors = ["ct0r"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
